# Generated by Django 4.2.7 on 2023-12-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=300)),
                ('resource_name', models.CharField(max_length=50)),
                ('resource_url', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=300)),
                ('text', models.CharField(max_length=1000)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
