# Generated by Django 4.2.7 on 2023-12-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='resource_url',
            new_name='dete',
        ),
    ]
