# Generated by Django 4.2.7 on 2023-12-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_resource_url_article_dete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='dete',
            new_name='date',
        ),
    ]
